default:
  image: cyclenerd/google-cloud-gcp-tools-container:latest

variables:
  WIF_PROVIDER: projects/788468196583/locations/global/workloadIdentityPools/gitlab-com/providers/gitlab-com-oidc
  SERVICE_ACCOUNT: gitlab-ci@workload-identity-353718.iam.gserviceaccount.com
  GOOGLE_CREDENTIALS: gcp_temp_cred.json

stages:
  - auth

auth:
  stage: auth
  script:
    # Configure Workload Identity Federation via a credentials file.
    - echo ${CI_JOB_JWT_V2} > .ci_job_jwt_file
    - gcloud iam workload-identity-pools create-cred-config "${WIF_PROVIDER}"
      --service-account="${SERVICE_ACCOUNT}"
      --output-file="${GOOGLE_CREDENTIALS}"
      --credential-source-file=.ci_job_jwt_file
    - gcloud config set auth/credential_file_override "${GOOGLE_CREDENTIALS}"
     # Now you can run gcloud commands authenticated as the impersonated service account.
    - gcloud config list
    - gcloud storage cat gs://workload-identity-federation-read-test/test.txt
  when: manual