formatter: "markdown"
output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
settings:
  indent: 2
content: |-
  # Workload Identity Pool and Provider for GitLab

  This Terraform module creates a Workload Identity Pool and Provider for GitLab.

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}