name: "Google Cloud Auth"

on:
  workflow_dispatch:

jobs:
  google-cloud-auth:
    name: Workload Identity Federation
    runs-on: ubuntu-latest

    # Add "id-token" for Google Authentication
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
      
      # Configure Workload Identity Federation via a credentials file.
      - id: auth
        name: 🔐 Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/788468196583/locations/global/workloadIdentityPools/github/providers/action'
          service_account: 'github-action@workload-identity-353718.iam.gserviceaccount.com'
          export_environment_variables: true
      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: '🔧 Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      # Now you can run gcloud commands authenticated as the impersonated service account.

      - id: 'gcloud'
        name: 📥 Google Cloud CLI
        run: |
          gcloud config list